# Generated by Django 2.1 on 2018-08-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('audio_url', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Episode_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('rater_name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=120)),
                ('rss_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('rater_name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Show')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Show'),
        ),
    ]
