# Generated by Django 2.1 on 2018-08-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20180819_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RSS_feeds',
            new_name='RSS',
        ),
    ]
