# Generated by Django 2.1 on 2018-08-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20180819_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episode_Rating',
            new_name='EpisodeRating',
        ),
        migrations.RenameModel(
            old_name='RSS',
            new_name='RSSFeed',
        ),
        migrations.RenameModel(
            old_name='Show_Rating',
            new_name='ShowRating',
        ),
    ]
