# Generated by Django 2.1 on 2018-08-20 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20180819_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='show_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='rss',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='podcasts.RSSFeed'),
            preserve_default=False,
        ),
    ]
