# Generated by Django 2.1 on 2018-08-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('tumblr', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('personal_web', models.CharField(blank=True, max_length=150, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='tumblr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='episoderating',
            name='rater_name',
            field=models.CharField(default='guest', max_length=50),
        ),
        migrations.AlterField(
            model_name='episoderating',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='showrating',
            name='rater_name',
            field=models.CharField(default='guest', max_length=50),
        ),
        migrations.AddField(
            model_name='cast',
            name='shows',
            field=models.ManyToManyField(to='podcasts.Show'),
        ),
    ]
