# Generated by Django 2.1 on 2018-08-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_auto_20180822_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('tumblr', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('personal_web', models.CharField(blank=True, max_length=150, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('shows', models.ManyToManyField(to='podcasts.Show')),
            ],
        ),
        migrations.RemoveField(
            model_name='cast',
            name='shows',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
