# Generated by Django 2.1 on 2018-08-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_auto_20180823_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
