# Generated by Django 2.1 on 2018-10-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0014_show_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_ids', to='podcasts.Show'),
        ),
    ]
